version: '3.8'

services:
  legal-qa-app:
    build: .
    ports:
      - "80:80"
    environment:
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
    env_file:
      - backend/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Development services (uncomment for local development)
  # frontend-dev:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:8000
  #   depends_on:
  #     - backend-dev

  # backend-dev:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./backend:/app
  #   environment:
  #     - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
  #   env_file:
  #     - backend/.env 